@startuml
	(A)
	(B)
	(C)
	(D)
	(E)
	(F)
	(G)
	F -- G : 1
	B -- D : 2
	C -- D : 2
	D -- B : 2
	E -- G : 2
	A -- B : 3
	C -- F : 3
	A -- C : 5
	E -- F : 5
	A -- D : 6
	C -- E : 6
	D -- A : 6
	C -- G : 7
	D -- F : 9
@enduml