@startuml
	(A)
	(B)
	(C)
	(D)
	(E)
	(F)
	(G)
	(H)
	A --> B : 9
	A --> C : 14
	A --> D : 15

	B --> A : 9
	B --> F : 24

	C --> A : 14
	C --> D : 5
	C --> E : 30
	C --> F : 18

	D --> A : 15
	D --> C : 5
	D --> E : 20
	D --> H : 44

	E --> C : 30
	E --> D : 20
	E --> F : 2
	E --> G : 11
	E --> H : 16

	F --> B : 24
	F --> C : 18
	F --> E : 2
	F --> G : 6
	F --> H : 19

	G --> E : 11
	G --> F : 6
	G --> H : 6

	H --> D : 44
	H --> E : 16
	H --> F : 19
	H --> G : 6

@enduml