@startuml
	(A)
	(B)
	(C)
	(D)
	(E)
	(F)
	(G)
	(H)
	E -- F : 2
	C -- D : 5
	F -- G : 6
	G -- H : 6
	A -- B : 9
	E -- G : 11
	A -- C : 14
	A -- D : 15
	E -- H : 16
	C -- F : 18
	F -- H : 19
	D -- E : 20
	B -- F : 24
	C -- E : 30
	D -- H : 44
@enduml