@startuml
	(San_Francisco)
	(Seattle)
	(Minneapolis)
	(Chicago)
	(Wash_DC)
	(New_York)
	(Los_Angelos)
	(Denver)
	(Dallas)
	(Las_Vegas)
	(Miami)
	(Boston)
	New_York -- Boston : 338
	Wash_DC -- New_York : 383
	Los_Angelos -- Las_Vegas : 435
	San_Francisco -- Los_Angelos : 629
	Minneapolis -- Chicago : 661
	Wash_DC -- Boston : 725
	San_Francisco -- Las_Vegas : 919
	Chicago -- Wash_DC : 1145
	Denver -- Las_Vegas : 1225
	Denver -- Dallas : 1258
	San_Francisco -- Seattle : 1306
	Minneapolis -- Denver : 1483
	Minneapolis -- Dallas : 1532
	Chicago -- Boston : 1613
	Wash_DC -- Miami : 1709
	Dallas -- Las_Vegas : 1983
	Wash_DC -- Dallas : 2113
	New_York -- Miami : 2145
	Seattle -- Denver : 2161
	Dallas -- Miami : 2161
	Seattle -- Minneapolis : 2661
@enduml